### ISSUE TITLE
Invalid domains on list

### ISSUE THREAD

**Issue by okjustin** [FiltersHeroes/KADhosts#48] opened 2022-05-08 14:05 UTC
Hello,

I just wanted to bring it to your attention that PiHole has flagged the following domains from your list as invalid:

`www.|movieonlives.com`
`|movieonlives.com`

Thanks

**Comment by hawkeye116477** [comment] 2022-05-08 14:16
It's duplicate of https://github.com/FiltersHeroes/KAD/issues/2108.

**Closed by hawkeye116477** 2022-05-08 14:16 UTC
Labels: duplicate, accepted

**Comment by krystian3w** [comment] 2022-11-23 07:08
Duplicate of https://github.com/FiltersHeroes/KAD/issues/2108
