### ISSUE TITLE
Invalid domains

### ISSUE THREAD

**Issue by lmmo** [FiltersHeroes/KADhosts#31] opened 2020-06-26 20:51 UTC
There are two invalid domains. I get the following error message:

```
  [i] Target: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts_without_controversies.txt
  [✓] Status: Retrieval successful
  [i] Received 10879 domains, 2 domains invalid!
      Sample of invalid domains:
      - getin-secure-bank.xyz‎
      - www.getin-secure-bank.xyz‎`
```

**Comment by krystian3w** [comment] 2020-06-28 13:51
Fixed:

https://github.com/PolishFiltersTeam/KAD/issues/1418

**Comment by krystian3w** [comment] 2020-06-28 13:52
Duplicate of https://github.com/PolishFiltersTeam/KAD/issues/1418

**Comment by krystian3w** [comment] 2020-06-28 13:54
Guilty was https://en.wikipedia.org/wiki/Left-to-right_mark

http://getin-secure-bank.xn--xyz-7t7s/

**Closed by krystian3w** 2020-06-28 13:54 UTC
Labels: bug, duplicate, accepted

**Comment by lmmo** [comment] 2020-06-28 14:02
Great!
